### ISSUE TITLE
init方法token获取不到

### ISSUE THREAD

**Issue by zhoucan38** [plat10510/cordova-plugin-umengpush#1]
```
    public void init(JSONArray args, final  CallbackContext callbackContext){
        SharedPreferences tokenSP = this.cordova.getContext().getSharedPreferences("mytoken", 0);
        String token = tokenSP.getString("token","");
        if(!tokenSP.getString("token","").equals("")){
            callbackContext.success(tokenSP.getString("token",""));
        }else{
            callbackContext.error("获取token失败");
        }
    }
```
        源代码中tokenSP定义缺少 SharedPreferences，编译报错。
       编译成功后调用init一直获取不到token，我不知道是不是UMApplication中onCreate没有调用，还是整个ionic工程还要修改哪个地方，友盟创建应用的包名我是随便起的，有影响么，这个需要和工程的一些地方对应么？
       android没搞过，不知道cordova插件如何调试，希望能帮我看看，感谢

**Comment by plat10510** [comment]
代码更新了，谢谢提醒。
包名应该要一致才行，再试试看。

**Comment by yarnbyte** [comment]
> ```
>     public void init(JSONArray args, final  CallbackContext callbackContext){
>         SharedPreferences tokenSP = this.cordova.getContext().getSharedPreferences("mytoken", 0);
>         String token = tokenSP.getString("token","");
>         if(!tokenSP.getString("token","").equals("")){
>             callbackContext.success(tokenSP.getString("token",""));
>         }else{
>             callbackContext.error("获取token失败");
>         }
>     }
> ```
> ```
>     源代码中tokenSP定义缺少 SharedPreferences，编译报错。
>    编译成功后调用init一直获取不到token，我不知道是不是UMApplication中onCreate没有调用，还是整个ionic工程还要修改哪个地方，友盟创建应用的包名我是随便起的，有影响么，这个需要和工程的一些地方对应么？
>    android没搞过，不知道cordova插件如何调试，希望能帮我看看，感谢
> ```

代码更新了，谢谢提醒。
包名应该要一致才行，再试试看。
