### ISSUE TITLE
第三方厂商通道收到的消息可以打开APP 但是无法获取消息内容

### ISSUE THREAD

**Issue by Shadowlong** [plat10510/cordova-plugin-umengpush#10]
接入的小米厂商通道, 填写了Activity, 可以正常的收到消息, 点击通知后也可以正常打开 APP, 但是无法获取到消息的内容.
`UMengPush.onSubscriptNotification(function(data){
  //点击通知就会触发这里的代码
  alert(JSON.stringify(data));
});
`
这里好像是没有回调. 但是通过非厂商通道发来的消息这里执行是正常的.

**Comment by yarnbyte** [comment]
希望您可以再看看我的说明文档
https://github.com/plat10510/cordova-plugin-umengpush#%E6%9C%80%E6%96%B0%E6%9B%B4%E6%96%B0

**Comment by Shadowlong** [comment]
收到! 非常感谢! 未来会支持这个功能吗?

**Comment by yarnbyte** [comment]
等到友盟支持了我就更新
