### ISSUE TITLE
你好，请问你开发时候是基于哪个cordova版本，麻烦看看下面错误怎么解决，谢谢

### ISSUE THREAD

**Issue by xiyuan-code** [plat10510/cordova-plugin-umengpush#11]
你好，请问你开发时候是基于哪个cordova版本，目前我用的是cordova7.1.0   报错：
/platforms/android/gradlew: Command failed with exit code 1 Error output:
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
/Users/xiyuan/webServer/wwwroot/cordova/dominos/ali_push/platforms/android/src/com/yl/umeng/UMengPush.java:62: 错误: 找不到符号
        cordova.getContext().registerReceiver(uPushBroadcastReceiver,notificationIntentFilter);
               ^
  符号:   方法 getContext()
  位置: 类型为CordovaInterface的变量 cordova
/Users/xiyuan/webServer/wwwroot/cordova/dominos/ali_push/platforms/android/src/com/yl/umeng/UMengPush.java:69: 错误: 找不到符号
            cordova.getContext().unregisterReceiver(uPushBroadcastReceiver);
                   ^
  符号:   方法 getContext()
  位置: 类型为CordovaInterface的变量 cordova
/Users/xiyuan/webServer/wwwroot/cordova/dominos/ali_push/platforms/android/src/com/yl/umeng/UMengPush.java:91: 错误: 找不到符号
        tokenSP = this.cordova.getContext().getSharedPreferences("mytoken", 0);
                              ^
  符号:   方法 getContext()
  位置: 类型为CordovaInterface的变量 cordova
3 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by xiyuan-code** [comment]
貌似cordova.getContext() 方法有问题

**Comment by yarnbyte** [comment]
这个是用AS打包的吗

**Comment by xiyuan-code** [comment]
你好，我就是装的cordova7.1.0 打包是直接用的 cordova build --release，谢谢

**Comment by yarnbyte** [comment]
用AS打包试试，先在ionic项目里用cordvoa platform add android，再用AS打开ionic项目里platforms里的android，因为有第三方依赖。
