### ISSUE TITLE
你好！cordova7.1.0中出现下面提示，并且安装后。init后获取token报错：获取token失败

### ISSUE THREAD

**Issue by xiyuan-code** [plat10510/cordova-plugin-umengpush#12]
:transformClassesWithDexForReleasewarning: Ignoring InnerClasses attribute for an anonymous inner class
(com.huawei.hms.support.api.push.a) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.huawei.hms.support.api.push.a.b.b) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.huawei.hms.support.api.push.a.c.g) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.huawei.hms.api.a) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

**Comment by yarnbyte** [comment]
看着有点像jar包冲突，你有没有安装其他推送插件？

**Comment by xiyuan-code** [comment]
没有的，我专门创建了一个项目来安装的。请问你开发时候是基于什么环境，是否可以基于7.1.0版本测试下，如果没问题，请把项目压缩zip发我邮箱 server@xiyuan.name 谢谢🙏
