### ISSUE TITLE
cordova 8.1.2版本安卓编译成功，但是安装apk闪退

### ISSUE THREAD

**Issue by GitHub19940510** [plat10510/cordova-plugin-umengpush#13]
您好，
   cordova 8.1.2版本安卓编译成功，但是安装apk闪退。这边是什么问题呢？ios 是不会有这个问题的 并且可以收到推送。。安卓这边的话，按照你这个步骤来的，还有什么其他的操作吗？

**Comment by yarnbyte** [comment]
是bug,已经更新了，重新安装一下插件
