### ISSUE TITLE
这个好像不支持ionic1.x

### ISSUE THREAD

**Issue by xuzixian** [plat10510/cordova-plugin-umengpush#17]
你好，这个好像不支持ionic1.x是吗

**Comment by yarnbyte** [comment]
应该是吧，我没用过ionic 1

**Comment by xuzixian** [comment]
那这个对cordova以及cordova-Android的版本有什么要求吗，我试过用cordova@6.5.0、cordova@9.0.0、cordova@8.1.2都不能打包，然后在plugin.xml里也没有看到版本要求，你能提供一下相应的版本要求吗，谢谢

**Comment by yarnbyte** [comment]
我使用的cordova也是8.1.2, Cordova Platforms: android 7.1.4, ios 4.5.5
或许你可以提供一下你的报错信息

**Comment by xuzixian** [comment]
报 程序包android.support.v4.app不存在
![image](https://user-images.githubusercontent.com/5772313/83935796-a0803300-a7ef-11ea-8a66-e9c15b487153.png)

**Comment by xuzixian** [comment]
对于我这种不懂安卓原生的人来说，简直就是灾难

**Comment by yarnbyte** [comment]
用使用as打试试




| |
罗远力
邮箱：plat10510@163.com
|

签名由 网易邮箱大师 定制

在2020年06月06日 12:18，xuzixian 写道：

报 程序包android.support.v4.app不存在

**Comment by xuzixian** [comment]
没辙了，as打开还是报android.support.v4.app不存在，解决后又报这个错误，
![image](https://user-images.githubusercontent.com/5772313/83937875-ff02dc80-a802-11ea-8078-fc6ad89d619b.png)
后面把这个的new NotificationCompat.Builder(context, id)，id参数去掉后能运行，但还是报一堆错误，然后提示获取token失败


W/NAccs.MsgDistribute:  handBroadCastMsg not handled command
V/my_token: 推送服务注册失败
    s=-11
    s1=accs bindapp error!
V/xiaomi: [Thread:2025] receive an intent from server, action=com.xiaomi.mipush.ERROR
V/xiaomi: receive a error message. code = 70000001, msg=  the push is not connected.
V/xiaomi: [Thread:2025] begin execute onCommandResult, command=Registration, resultCode=70000001, reason= the push is not connected.

**Comment by yarnbyte** [comment]
so文件冲突，这个比较难整，但是我文档里有写过怎么解决，要不你试试运气




| |
罗远力
邮箱：plat10510@163.com
|

签名由 网易邮箱大师 定制

在2020年06月06日 14:46，xuzixian 写道：

没辙了，as打开还是报android.support.v4.app不存在，解决后又报这个错误，

后面把这个的new NotificationCompat.Builder(context, id)，id参数去掉后能运行，但还是报一堆错误，然后提示获取token失败

W/NAccs.MsgDistribute: handBroadCastMsg not handled command
V/my_token: 推送服务注册失败
s=-11
s1=accs bindapp error!
V/xiaomi: [Thread:2025] receive an intent from server, action=com.xiaomi.mipush.ERROR
V/xiaomi: receive a error message. code = 70000001, msg= the push is not connected.
V/xiaomi: [Thread:2025] begin execute onCommandResult, command=Registration, resultCode=70000001, reason= the push is not connected.
