### ISSUE TITLE
如何获得消息传给app的参数呢

### ISSUE THREAD

**Issue by chenbont** [plat10510/cordova-plugin-umengpush#2]
谢谢作者，我的app现在已经能收到推送了，但是我应该如何让app响应消息呢？在点击消息打开app后，app的resume事件能触发，但我没办法获得参数

**Comment by yarnbyte** [comment]
> 谢谢作者，我的app现在已经能收到推送了，但是我应该如何让app响应消息呢？在点击消息打开app后，app的resume事件能触发，但我没办法获得参数

下一步我会继续完善这个功能

**Comment by yarnbyte** [comment]
这回把获取参数加上了，问题我先关闭了。
