### ISSUE TITLE
请问厂商通道这里是怎么用的

### ISSUE THREAD

**Issue by xiaofan020** [plat10510/cordova-plugin-umengpush#4]
比如华为怎么去获取token

**Comment by xiaofan020** [comment]
明白了，是友盟那边帮推送到厂商通道了。我用logcat查看厂商通道能注册成功并打印出token

**Comment by yarnbyte** [comment]
那我可以关闭了吗？

**Comment by xiaofan020** [comment]
测试发现小米能接收到推送消息，但是点击通知栏的消息不能跳转到APP，MIUI 10.8.11.22

**Comment by yarnbyte** [comment]
> 测试发现小米能接收到推送消息，但是点击通知栏的消息不能跳转到APP，MIUI 10.8.11.22

需要把mipush项加上，后台发送推送的时候，组装推送数据的时候，需要有mipush，值写你的MainActivity的包名，比如我的是包名是com.yl.test，那就写com.yl.test.MainActivity. 不知道你用的是什么作为后台推送服务。
![image](https://user-images.githubusercontent.com/35519025/60250859-fd921a00-98f9-11e9-8118-7c7f8d78dc50.png)

![image](https://user-images.githubusercontent.com/35519025/60250904-1bf81580-98fa-11e9-8e1e-be179c08ba1d.png)

或者你从友盟发推送，并把跳转到指定路径设置上试试。
![image](https://user-images.githubusercontent.com/35519025/60251003-4ba71d80-98fa-11e9-9c74-8d8bcd8b196f.png)

**Comment by xiaofan020** [comment]
嗯，包名.MainActivity确实可以了！谢谢

**Comment by xiaofan020** [comment]
感觉小米的有时候推送是接收不到的，不知道是不是要使用小米的弹窗功能才能保证达到率

**Comment by yarnbyte** [comment]
> 感觉小米的有时候推送是接收不到的，不知道是不是要使用小米的弹窗功能才能保证达到率

目前没遇到过这种情况

**Comment by xiaofan020** [comment]
大神，又来麻烦你了。魅族系统你那边目前正常不？我这里集成进去，注册系统通道好像不成功，日志里没有看到魅族pushid。设备在线时使用友盟device_token推送消息也未弹出消息通知，看日志有收到消息，但是没显示通知。APP相关通知栏权限已经开了的。是还有哪里需要设置不

**Comment by xiaofan020** [comment]
好像通过友盟的推送都没有显示通知了

**Comment by xiaofan020** [comment]
今天早上重新测试又莫名其妙好了

**Comment by xiaofan020** [comment]
大神，友盟push新版有了OPPO，vivo厂商通道，能帮忙集成进去不
