### ISSUE TITLE
安装以后打包提示'UMCommon/UMCommon.h' file not found

### ISSUE THREAD

**Issue by C-racker** [plat10510/cordova-plugin-umengpush#5]
小白请教一下
我是直接运行安装的，直接打包会提示找不到这个文件，但是查看是有这个文件的。
```
cordova plugin add cordova-plugin-umengpush --variable IOS_APPKEY=xxx --variable UM_APPKEY=xxx --variable UM_MESSAGE_SECRET=xxx --variable XIAOMI_ID=xxx --variable XIAOMI_KEY=YOUR_XIAOMI_KEY --variable MEIZU_APPID=xxx --variable MEIZU_APPKEY=xxx
```

**Comment by yarnbyte** [comment]
> 小白请教一下
> 我是直接运行安装的，直接打包会提示找不到这个文件，但是查看是有这个文件的。
> 
> ```
> cordova plugin add cordova-plugin-umengpush --variable IOS_APPKEY=xxx --variable UM_APPKEY=xxx --variable UM_MESSAGE_SECRET=xxx --variable XIAOMI_ID=xxx --variable XIAOMI_KEY=YOUR_XIAOMI_KEY --variable MEIZU_APPID=xxx --variable MEIZU_APPKEY=xxx
> ```

应该是UMCommon.framework这个文件上传到npm丢失了Headers文件，解决办法是把我代码从Github下载到你本地，再替换你cordova项目里的这个插件

**Comment by C-racker** [comment]
> > 小白请教一下
> > 我是直接运行安装的，直接打包会提示找不到这个文件，但是查看是有这个文件的。
> > ```
> > cordova plugin add cordova-plugin-umengpush --variable IOS_APPKEY=xxx --variable UM_APPKEY=xxx --variable UM_MESSAGE_SECRET=xxx --variable XIAOMI_ID=xxx --variable XIAOMI_KEY=YOUR_XIAOMI_KEY --variable MEIZU_APPID=xxx --variable MEIZU_APPKEY=xxx
> > ```
> 
> 应该是UMCommon.framework这个文件上传到npm丢失了Headers文件，解决办法是把我代码从Github下载到你本地，再替换你cordova项目里的这个插件

感谢回复，我把*.framework/Versions/A/ 下的Headers和SDK文件移动到*.framework目录下问题就解决了，应该是不同路径导致不识别造成的

**Comment by yarnbyte** [comment]
> > > 小白请教一下
> > > 我是直接运行安装的，直接打包会提示找不到这个文件，但是查看是有这个文件的。
> > > ```
> > > cordova plugin add cordova-plugin-umengpush --variable IOS_APPKEY=xxx --variable UM_APPKEY=xxx --variable UM_MESSAGE_SECRET=xxx --variable XIAOMI_ID=xxx --variable XIAOMI_KEY=YOUR_XIAOMI_KEY --variable MEIZU_APPID=xxx --variable MEIZU_APPKEY=xxx
> > > ```
> > 
> > 
> > 应该是UMCommon.framework这个文件上传到npm丢失了Headers文件，解决办法是把我代码从Github下载到你本地，再替换你cordova项目里的这个插件
> 
> 感谢回复，我把.framework/Versions/A/ 下的Headers和SDK文件移动到sdk.framework目录下问题就解决了，应该是不同路径导致不识别造成的

ok
