### ISSUE TITLE
ionic4安装后打包报错

### ISSUE THREAD

**Issue by mlh1421** [plat10510/cordova-plugin-umengpush#6]
报错如下：

`Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
[ERROR] An error occurred while running subprocess cordova.

        cordova build android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.`
环境如下：
` cordova platform ls
Installed platforms:
  android 8.0.0
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0
`
cordova版本 :9.0.0

**Comment by yarnbyte** [comment]
> 报错如下：
> 
> `Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
> [ERROR] An error occurred while running subprocess cordova.
> 
> ```
>     cordova build android exited with exit code 1.
> 
>     Re-running this command with the --verbose flag may provide more information.`
> ```
> 
> 环境如下：
> `cordova platform ls Installed platforms: android 8.0.0 Available platforms: browser ^6.0.0 electron ^1.0.0 ios ^5.0.0 osx ^5.0.0 windows ^7.0.0`
> cordova版本 :9.0.0

还没支持到Cordova 9，要过段时间我才能继续更新了。
