### ISSUE TITLE
讨论一下plugin.xml 的参数配置

### ISSUE THREAD

**Issue by XYFBingo** [plat10510/cordova-plugin-umengpush#8]

**Comment by XYFBingo** [comment]
xml里有 UM_APPKEY 和 UM_MESSAGE_SECRET的配置，
 meta-data android:name="UM_APPKEY" android:value="$UM_APPKEY"
 meta-data android:name="UM_MESSAGE_SECRET" android:value="$UM_MESSAGE_SECRET"
但是没有小米XIAOMI_ID、XIAOMI_KEY、华为等的配置，这样的话，用cordova plugin add cordova-plugin-umengpush --variable XIAOMI_ID=YOUR_XIAOMI_ID --variable XIAOMI_KEY=YOUR_XIAOMI_KEY 这种方式设置真的可以吗？

**Comment by yarnbyte** [comment]
> xml里有 UM_APPKEY 和 UM_MESSAGE_SECRET的配置，
> meta-data android:name="UM_APPKEY" android:value="$UM_APPKEY"
> meta-data android:name="UM_MESSAGE_SECRET" android:value="$UM_MESSAGE_SECRET"
> 但是没有小米XIAOMI_ID、XIAOMI_KEY、华为等的配置，这样的话，用cordova plugin add cordova-plugin-umengpush --variable XIAOMI_ID=YOUR_XIAOMI_ID --variable XIAOMI_KEY=YOUR_XIAOMI_KEY 这种方式设置真的可以吗？

感谢指出，其实我自己用的时候都是写死的，只是后来也想拿出来给大家用，代码改了一些，有一些就遗漏了。

**Comment by yarnbyte** [comment]
插件已更新
