### ISSUE TITLE
cordova 8.0中build 报错 async 不存在，但是在项目中安装async 后，打包成功，但是启动闪退

### ISSUE THREAD

**Issue by xiyuan-code** [plat10510/cordova-plugin-umengpush#9]
**报错信息：**
xiyuan~/webServer/wwwroot/cordova/dominos/push_test$ cordova build --release
Android Studio project detected
(node:4750) UnhandledPromiseRejectionWarning: Error: Cannot find module 'async'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at module.exports (/Users/xiyuan/webServer/wwwroot/cordova/dominos/push_test/plugins/cordova-plugin-umengpush/scripts/addcustommirror.js:6:17)
    at runScriptViaModuleLoader (/Users/xiyuan/.nvm/versions/node/v10.12.0/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:18)
    at runScript (/Users/xiyuan/.nvm/versions/node/v10.12.0/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:164:16)
    at /Users/xiyuan/.nvm/versions/node/v10.12.0/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:20

**另外我想咨询下，这个友盟push插件支持cordova7.1.0吗？我发现 进行cordova clean 也报错：**
* Where:
Script '/Users/xiyuan/webServer/wwwroot/cordova/dominos/IOS_Android_UAT/platforms/android/cordova-plugin-umengpush/mobile-plugin.gradle' line: 9

* What went wrong:
A problem occurred evaluating script.
> Could not find method api() for arguments [com.umeng.umsdk:common:1.5.4] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by yarnbyte** [comment]
> **报错信息：**
> xiyuan~/webServer/wwwroot/cordova/dominos/push_test$ cordova build --release
> Android Studio project detected
> (node:4750) UnhandledPromiseRejectionWarning: Error: Cannot find module 'async'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
> at Function.Module._load (internal/modules/cjs/loader.js:506:25)
> at Module.require (internal/modules/cjs/loader.js:636:17)
> at require (internal/modules/cjs/helpers.js:20:18)
> at module.exports (/Users/xiyuan/webServer/wwwroot/cordova/dominos/push_test/plugins/cordova-plugin-umengpush/scripts/addcustommirror.js:6:17)
> at runScriptViaModuleLoader (/Users/xiyuan/.nvm/versions/node/v10.12.0/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:18)
> at runScript (/Users/xiyuan/.nvm/versions/node/v10.12.0/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:164:16)
> at /Users/xiyuan/.nvm/versions/node/v10.12.0/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:20
> 
> **另外我想咨询下，这个友盟push插件支持cordova7.1.0吗？我发现 进行cordova clean 也报错：**
> 
> * Where:
>   Script '/Users/xiyuan/webServer/wwwroot/cordova/dominos/IOS_Android_UAT/platforms/android/cordova-plugin-umengpush/mobile-plugin.gradle' line: 9
> * What went wrong:
>   A problem occurred evaluating script.
> 
> > Could not find method api() for arguments [com.umeng.umsdk:common:1.5.4] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```
npm i async
```
试试看

**Comment by xiyuan-code** [comment]
谢谢你能回到我的问题，我先尝试修改源码来熟悉cordova组件的编写
